class Quizzes{
  String title,quizNumber,id;
  int createdOn,startTime,endTime;
  double duration;
  List<String> instructions;
  List<Map<String, dynamic>>questions;


  Quizzes({this.title, this.quizNumber, this.id, this.createdOn, this.duration,
      this.instructions, this.questions,this.endTime,this.startTime});

  Map<String, dynamic> toMap() {
    var map = Map<String, dynamic>();
    map['title'] = title;
    map['questions'] = questions;
    map['id'] = id;
    map['createdOn'] = createdOn;
    map['quizNumber'] = quizNumber;
    map['duration'] = duration;
    map['instructions'] = instructions;
    map['endTime'] = endTime;
    map['startTime'] = startTime;
    return map;
  }

  Quizzes.fromMapObject(Map<String, dynamic> map) {
    this.title = map['title'];
    this.questions = map['questions'];
    this.id = map['id'];
    this.createdOn = map['createdOn'];
    this.quizNumber = map['quizNumber'];
    this.instructions = map['instructions'];
    this.duration = map['duration'];
    this.startTime = map['startTime'];
    this.endTime = map['endTime'];
  }
}
List<Quizzes>quizzes=[
  Quizzes(
    quizNumber: 'Quiz 1',
    id: 'ynhsksTjkGkajIkaPba78T',
   title: 'Fundamentals of Computer Quiz',
    instructions: [
      'Answer All Questions',
      'Select the Correct Answers only and submit after answering all',
      'Quiz will automatically Submit when there is time up',
      'Quiz can be attempted only once'
    ],
    startTime: 1631614500000,
    endTime: 1630314000000,
    createdOn: 1630303200000,
    duration: 60,
    questions: [
      {
        'id':1,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':2,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':3,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':4,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':5,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':6,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':7,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':8,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':9,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':10,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':11,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':12,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':13,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':14,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':15,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':16,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':17,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':18,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':19,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':20,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':21,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':22,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':23,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':24,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':25,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':26,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':27,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':28,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':29,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':30,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':31,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':32,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':33,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':34,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':35,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':36,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
    ]
  ),
  Quizzes(
    quizNumber: 'Quiz 2',
    id: 'yn23ksTjkTkajIkajba78T',
   title: 'Information Recycling',
    instructions: [
      'Answer All Questions',
      'Select the Correct Answers only and submit after answering all',
      'Quiz will automatically Submit when there is time up',
      'Quiz can be attempted only once'
    ],
    startTime: 1630309200000,
    endTime: 1630314000000,
    createdOn: 1630303200000,
    duration: 30,
    questions: [
      {
        'id':1,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':2,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':3,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':4,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':5,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':6,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':7,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':8,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':9,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':10,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':11,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':12,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':13,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':14,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':15,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':16,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':17,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':18,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':19,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':20,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':21,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':22,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':23,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':24,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':25,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':26,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':27,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':28,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':29,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':30,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':31,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':32,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':33,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':34,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':35,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':36,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
    ]
  ),
  Quizzes(
    quizNumber: 'Quiz 3',
    id: 'jn33ksTjkTkajIkajba9hT',
   title: 'Computer Hardware',
    instructions: [
      'Answer All Questions',
      'Select the Correct Answers only and submit after answering all',
      'Quiz will automatically Submit when there is time up',
      'Quiz can be attempted only once'
    ],
    startTime: 1630309200000,
    endTime: 1630314000000,
    createdOn: 1630303200000,
    duration: 30,
    questions: [
      {
        'id':1,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':2,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':3,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':4,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':5,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':6,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':7,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':8,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':9,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':10,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':11,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':12,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':13,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':14,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':15,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':16,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':17,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':18,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':19,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':20,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':21,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':22,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':23,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':24,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':25,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':26,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':27,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':28,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':29,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':30,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
      {
        'id':31,
        'score':3,
        'question':"ICT stands for ?",
        'optionA':"Inter connected Terminals",
        'optionB':"Intera Common Terminology",
        'optionC':"International Communication Technology",
        'optionD':"Information and Communication Technology",
        'answer':"Information and Communication Technology",
      },
      {
        'id':32,
        'score':3,
        'question':"Which of the following is the appropriate definition of Information Technology?",
        'optionA':"Information Technology refers to the use of hardware and software for processing information",
        'optionB':"Information Technology refers to the use of hardware and software for distribution of useful information",
        'optionC':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
        'optionD':"Information Technology refers to the use of principles of Physical sciences and Social sciences for processing of information of many kinds.",
        'answer':"Information Technology refers to the use of hardware and software for storage, retrieval, processing and distributing information of many kinds.",
      },
      {
        'id':33,
        'score':3,
        'question':"Which of the following statements is NOT correct ?",
        'optionA':"Computer is capable of processing only digital signal",
        'optionB':"Appropriate software is required for processing the data",
        'optionC':"Computer is capable of processing digital as well as analog signals",
        'optionD':"Computer is capable of analysing both quantitative and qualitative data",
        'answer':"Computer is capable of processing only digital signal",
      },
      {
        'id':34,
        'score':3,
        'question':"Which of the following is correct statement ?",
        'optionA':"A set of instructions is called a programme",
        'optionB':"Computers can be used for diagnosing the difficulty of a student in learning a subject",
        'optionC':"Psychological testing can be done with the help of computer provided software is available",
        'optionD':"All of the above",
        'answer':"All of the above",
      },
      {
        'id':35,
        'score':3,
        'question':"Which of the following statements is correct ?",
        'optionA':"Virus is a part of software",
        'optionB':"Virus is an operating system",
        'optionC':"Internet does not allow the virus to spread",
        'optionD':"Virus improves the speed of processing information through computer",
        'answer':"Virus is a part of software",
      },
      {
        'id':36,
        'score':3,
        'question':"Which of the following is not the characteristic of a computer ?",
        'optionA':"computer cannot think at its own",
        'optionB':"computer is an electrical machine",
        'optionC':"computer processes information error free",
        'optionD':"computer can hold data for any length of time",
        'answer':"computer is an electrical machine",
      },
    ]
  ),
];